name: 'DotCover Github Actions wrapper'
description: 'Run DotCover in Github Actions. Includes .NET 6.0 SDK'
inputs:
  dotCoverCommand:
    description: "Command to pass to DotCover"
  configFile:
    description: "Path to a config file"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.dotCoverCommand }}
  - ${{ inputs.configFile }}
